Movie/Movie/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from Movie import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Movie_List.urls'))
]


urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Movie/Movie_List/urls.py
from django.urls import path
from .views import home, detail, MovieList, detail_series, SeriesList, SearchList

app_name = "movie"
urlpatterns = [
    path('', home, name="home"),
    path('detail-movie/<slug:slug>', detail, name='detail'),
    path('all-movie/page/<int:page>', MovieList.as_view(), name='movie-list'),
    path('detail-series/<slug:slug>', detail_series, name='detail-series'),
    path('all-series/page/<int:page>', SeriesList.as_view(), name='series-list'),
    path('search/', SearchList.as_view(), name="search"),
    path("search/page/<int:page>", SearchList.as_view(), name="search"),

]

Movie/Movie_Account/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    pass

Movie/Movie_List/models.py
from django.db import models
from django.utils import timezone
from embed_video.fields import EmbedVideoField



class Movie(models.Model):
    title = models.CharField(max_length=200, verbose_name="Movie Name")
    slug = models.SlugField(max_length=200, verbose_name="Name in URL")
    imdb = models.CharField(max_length=10, verbose_name="IMDB")
    genre = models.TextField(verbose_name="Genres")
    publish = models.DateField(default=timezone.now, verbose_name="Publish Date")
    desc = models.TextField(verbose_name="About Movie")
    trailer = EmbedVideoField(verbose_name="Trailer", null=True, blank=True)
    download = models.URLField(verbose_name="480P")
    download2 = models.URLField(verbose_name="720P")
    download3 = models.URLField(verbose_name="1080P")
    img = models.ImageField(upload_to="media", verbose_name="Image")
    img2 = models.ImageField(upload_to="media", verbose_name="Detail Page Image (Big)")
    season = models.CharField(max_length=20, blank=True, null=True, verbose_name="Season?")
    time = models.CharField(max_length=100, verbose_name="Movie Time")
    director = models.CharField(max_length=100, verbose_name="Movie Director")
    stars = models.TextField(verbose_name="Stars")

    def __str__(self):
        return self.title


class Series(models.Model):
    title = models.CharField(max_length=200, verbose_name="Series Name")
    slug = models.SlugField(max_length=200, verbose_name="Name in URL")
    imdb = models.CharField(max_length=10, verbose_name="IMDB")
    genre = models.TextField(verbose_name="Genres")
    publish = models.DateField(default=timezone.now, verbose_name="Publish Date")
    desc = models.TextField(verbose_name="About Series")
    trailer = EmbedVideoField(verbose_name="Trailer", null=True, blank=True)
    img = models.ImageField(upload_to="media", verbose_name="Image")
    img2 = models.ImageField(upload_to="media", verbose_name="Detail Page Image (Big)")
    season = models.CharField(max_length=20, blank=True, null=True, verbose_name="Season?")
    director = models.CharField(max_length=100, verbose_name="Series Director")
    stars = models.TextField(verbose_name="Series Stars")
    status = models.BooleanField(default=True, verbose_name="Series Mode")

    def __str__(self):
        return self.title


class SeriesEpisode(models.Model):
    title = models.CharField(max_length=200, verbose_name="Series Name")
    season = models.IntegerField(blank=True, null=True, verbose_name="Season")
    episode = models.IntegerField(blank=True, null=True, verbose_name="Episode")
    series = models.ManyToManyField(Series, related_name="movies", verbose_name="Which Series?")
    download = models.URLField(verbose_name="720P")
    download2 = models.URLField(verbose_name="1080P")
    

    def __str__(self):
        return self.title

Movie/Movie_Account/views.py
from django.shortcuts import render

# Create your views here.

Movie/Movie_List/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView
from django.core.paginator import Paginator
from .models import Movie, Series, SeriesEpisode
from django.db.models import Q
from itertools import chain


def home(request):
    movie = Movie.objects.all()[:8]
    series = Series.objects.all()[:12]
    context = {
        'movie': movie,
        'series': series,
    }
    return render(request, 'home_page.html', context)


def detail(request, slug):
    movie = get_object_or_404(Movie, slug=slug)
    context = {
        'detail': movie
    }
    return render(request, 'detail_movie.html', context)


class MovieList(ListView):
    model = Movie
    paginate_by = 10
    template_name = "view_all_movie.html"


#===========================> Series Section
def detail_series(request, slug):
    series = get_object_or_404(Series, slug=slug)
    context = {
        'detail': series
    }
    return render(request, 'detail_serires.html', context)


class SeriesList(ListView):
    model = Series
    paginate_by = 10
    template_name = "view_all_series.html"


#=====================================> Search Section
class SearchList(ListView):
    paginate_by = 10
    template_name = 'search_list.html'

    def get_queryset(self):
        search = self.request.GET.get('q')
        movie = Movie.objects.filter(Q(title__icontains=search) | Q(stars__icontains=search))
        series = Series.objects.filter(Q(title__icontains=search) | Q(stars__icontains=search))
        result = chain(movie, series)
        result_list = list(result)
        #or_lookup = (Q(title__icontains=search) | Q(stars__icontains=search))
        return result_list

    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['search'] = self.request.GET.get('q')
        return context

Movie/templates/home_page.html
{% extends 'shared/_Main_Layout.html' %}
{% load static %}

{% block content %}
	<!-- home -->
	<div class="home home--static">
		<div class="home__carousel owl-carousel" id="flixtv-hero">
		{% for mov in movie %}

			<div class="home__card">
				<a href="{% url 'movie:detail' mov.slug %}">
					<img src="{{mov.img.url}}" alt="">
				</a>
				<div>
					<h2>{{mov.title}}</h2>
					<ul>
						<li>{{mov.genre}}</li>
						<li>{{mov.publish}}</li>
					</ul>
				</div>
				<button class="home__add" type="button"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M16,2H8A3,3,0,0,0,5,5V21a1,1,0,0,0,.5.87,1,1,0,0,0,1,0L12,18.69l5.5,3.18A1,1,0,0,0,18,22a1,1,0,0,0,.5-.13A1,1,0,0,0,19,21V5A3,3,0,0,0,16,2Zm1,17.27-4.5-2.6a1,1,0,0,0-1,0L7,19.27V5A1,1,0,0,1,8,4h8a1,1,0,0,1,1,1Z"/></svg></button>
				<span class="home__rating"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M22,9.67A1,1,0,0,0,21.14,9l-5.69-.83L12.9,3a1,1,0,0,0-1.8,0L8.55,8.16,2.86,9a1,1,0,0,0-.81.68,1,1,0,0,0,.25,1l4.13,4-1,5.68A1,1,0,0,0,6.9,21.44L12,18.77l5.1,2.67a.93.93,0,0,0,.46.12,1,1,0,0,0,.59-.19,1,1,0,0,0,.4-1l-1-5.68,4.13-4A1,1,0,0,0,22,9.67Zm-6.15,4a1,1,0,0,0-.29.88l.72,4.2-3.76-2a1.06,1.06,0,0,0-.94,0l-3.76,2,.72-4.2a1,1,0,0,0-.29-.88l-3-3,4.21-.61a1,1,0,0,0,.76-.55L12,5.7l1.88,3.82a1,1,0,0,0,.76.55l4.21.61Z"/></svg>{{mov.imdb}}</span>
			</div>

		{% endfor %}
		</div>

		<button class="home__nav home__nav--prev" data-nav="#flixtv-hero" type="button"></button>
		<button class="home__nav home__nav--next" data-nav="#flixtv-hero" type="button"></button>
	</div>
	<!-- end home -->

	<!-- catalog -->
	<div class="catalog">
		<div class="container">
			<div class="row">
				<div class="col-12">
					<div class="catalog__nav">
						<div class="catalog__select-wrap">

							<h3 style="color:#fff; font-weight:normal;">All Movies</h3>
						</div>
					</div>

					<div class="row row--grid">
						{% for mov in movie %}
						<div class="col-6 col-sm-4 col-lg-3 col-xl-2">
							<div class="card">
								<a href="{% url 'movie:detail' mov.slug %}" class="card__cover">
									<img src="{{mov.img.url}}" alt="">
									<svg width="22" height="22" viewBox="0 0 22 22" fill="none" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" clip-rule="evenodd" d="M11 1C16.5228 1 21 5.47716 21 11C21 16.5228 16.5228 21 11 21C5.47716 21 1 16.5228 1 11C1 5.47716 5.47716 1 11 1Z" stroke-linecap="round" stroke-linejoin="round"/><path fill-rule="evenodd" clip-rule="evenodd" d="M14.0501 11.4669C13.3211 12.2529 11.3371 13.5829 10.3221 14.0099C10.1601 14.0779 9.74711 14.2219 9.65811 14.2239C9.46911 14.2299 9.28711 14.1239 9.19911 13.9539C9.16511 13.8879 9.06511 13.4569 9.03311 13.2649C8.93811 12.6809 8.88911 11.7739 8.89011 10.8619C8.88911 9.90489 8.94211 8.95489 9.04811 8.37689C9.07611 8.22089 9.15811 7.86189 9.18211 7.80389C9.22711 7.69589 9.30911 7.61089 9.40811 7.55789C9.48411 7.51689 9.57111 7.49489 9.65811 7.49789C9.74711 7.49989 10.1091 7.62689 10.2331 7.67589C11.2111 8.05589 13.2801 9.43389 14.0401 10.2439C14.1081 10.3169 14.2951 10.5129 14.3261 10.5529C14.3971 10.6429 14.4321 10.7519 14.4321 10.8619C14.4321 10.9639 14.4011 11.0679 14.3371 11.1549C14.3041 11.1999 14.1131 11.3999 14.0501 11.4669Z" stroke-linecap="round" stroke-linejoin="round"/></svg>
								</a>
								<button class="card__add" type="button"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M16,2H8A3,3,0,0,0,5,5V21a1,1,0,0,0,.5.87,1,1,0,0,0,1,0L12,18.69l5.5,3.18A1,1,0,0,0,18,22a1,1,0,0,0,.5-.13A1,1,0,0,0,19,21V5A3,3,0,0,0,16,2Zm1,17.27-4.5-2.6a1,1,0,0,0-1,0L7,19.27V5A1,1,0,0,1,8,4h8a1,1,0,0,1,1,1Z"/></svg></button>
								<span class="card__rating"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M22,9.67A1,1,0,0,0,21.14,9l-5.69-.83L12.9,3a1,1,0,0,0-1.8,0L8.55,8.16,2.86,9a1,1,0,0,0-.81.68,1,1,0,0,0,.25,1l4.13,4-1,5.68A1,1,0,0,0,6.9,21.44L12,18.77l5.1,2.67a.93.93,0,0,0,.46.12,1,1,0,0,0,.59-.19,1,1,0,0,0,.4-1l-1-5.68,4.13-4A1,1,0,0,0,22,9.67Zm-6.15,4a1,1,0,0,0-.29.88l.72,4.2-3.76-2a1.06,1.06,0,0,0-.94,0l-3.76,2,.72-4.2a1,1,0,0,0-.29-.88l-3-3,4.21-.61a1,1,0,0,0,.76-.55L12,5.7l1.88,3.82a1,1,0,0,0,.76.55l4.21.61Z"/></svg>{{mov.imdb}}</span>
								<h3 class="card__title"><a href="details.html">{{mov.title}}</a></h3>
								<ul class="card__list">
									<li>{{mov.genre|truncatewords:1}}</li>
									<li>{{mov.publish}}</li>
								</ul>
							</div>
						</div>
						{% endfor %}
					</div>
				</div>
			</div>		

			<div class="row">
				<div class="col-12">
					<a href="{% url 'movie:movie-list' page=1 %}" ><button class="catalog__more" type="button">Load more</button></a>
				</div>
			</div>
		</div>
	</div>
	<!-- end catalog -->

	<!-- subscriptions -->
	<section class="section">
		<div class="container">
			<div class="row">
				<div class="col-12">
					<h2 class="section__title">Recent Series</h2>
				</div>

				<div class="col-12">
					<div class="section__carousel-wrap">
						<div class="section__carousel owl-carousel" id="subscriptions">
						{% for ser in series %}
							<div class="card">
								<a href="{% url 'movie:detail-series' ser.slug %}" class="card__cover">
									<img src="{{ser.img.url}}" alt="">
									<svg width="20" height="16" viewBox="0 0 20 16" fill="none" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" clip-rule="evenodd" d="M13.1615 8.05308C13.1615 9.79908 11.7455 11.2141 9.9995 11.2141C8.2535 11.2141 6.8385 9.79908 6.8385 8.05308C6.8385 6.30608 8.2535 4.89108 9.9995 4.89108C11.7455 4.89108 13.1615 6.30608 13.1615 8.05308Z" stroke-linecap="round" stroke-linejoin="round"/><path fill-rule="evenodd" clip-rule="evenodd" d="M9.998 15.3549C13.806 15.3549 17.289 12.6169 19.25 8.05289C17.289 3.48888 13.806 0.750885 9.998 0.750885H10.002C6.194 0.750885 2.711 3.48888 0.75 8.05289C2.711 12.6169 6.194 15.3549 10.002 15.3549H9.998Z" stroke-linecap="round" stroke-linejoin="round"/></svg>
								</a>
								<button class="card__add" type="button"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M16,2H8A3,3,0,0,0,5,5V21a1,1,0,0,0,.5.87,1,1,0,0,0,1,0L12,18.69l5.5,3.18A1,1,0,0,0,18,22a1,1,0,0,0,.5-.13A1,1,0,0,0,19,21V5A3,3,0,0,0,16,2Zm1,17.27-4.5-2.6a1,1,0,0,0-1,0L7,19.27V5A1,1,0,0,1,8,4h8a1,1,0,0,1,1,1Z"/></svg></button>
								<h3 class="card__title card__title--subs"><a href="details.html">{{ser.title}}</a></h3>
								<ul class="card__list card__list--subs">
									<li>{{ser.director}}</li>
								</ul>
							</div>
						{% endfor %}	
						</div>

						<button class="section__nav section__nav--cards section__nav--prev" data-nav="#subscriptions" type="button"><svg width="17" height="15" viewBox="0 0 17 15" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M1.25 7.72559L16.25 7.72559" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/><path d="M7.2998 1.70124L1.2498 7.72524L7.2998 13.7502" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/></svg></button>
						<button class="section__nav section__nav--cards section__nav--next" data-nav="#subscriptions" type="button"><svg width="17" height="15" viewBox="0 0 17 15" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M15.75 7.72559L0.75 7.72559" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/><path d="M9.7002 1.70124L15.7502 7.72524L9.7002 13.7502" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/></svg></button>
					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- end subscriptions -->

	<!-- catalog -->
	<div class="catalog">
		<div class="container">
			<div class="row">
				<div class="col-12">
					<div class="catalog__nav">
						<div class="catalog__select-wrap">

							<h3 style="color:#fff; font-weight:normal;">All Series</h3>
						</div>
					</div>

					<div class="row row--grid">
						{% for mov in series %}
						<div class="col-6 col-sm-4 col-lg-3 col-xl-2">
							<div class="card">
								<a href="{% url 'movie:detail-series' mov.slug %}" class="card__cover">
									<img src="{{mov.img.url}}" alt="">
									<svg width="22" height="22" viewBox="0 0 22 22" fill="none" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" clip-rule="evenodd" d="M11 1C16.5228 1 21 5.47716 21 11C21 16.5228 16.5228 21 11 21C5.47716 21 1 16.5228 1 11C1 5.47716 5.47716 1 11 1Z" stroke-linecap="round" stroke-linejoin="round"/><path fill-rule="evenodd" clip-rule="evenodd" d="M14.0501 11.4669C13.3211 12.2529 11.3371 13.5829 10.3221 14.0099C10.1601 14.0779 9.74711 14.2219 9.65811 14.2239C9.46911 14.2299 9.28711 14.1239 9.19911 13.9539C9.16511 13.8879 9.06511 13.4569 9.03311 13.2649C8.93811 12.6809 8.88911 11.7739 8.89011 10.8619C8.88911 9.90489 8.94211 8.95489 9.04811 8.37689C9.07611 8.22089 9.15811 7.86189 9.18211 7.80389C9.22711 7.69589 9.30911 7.61089 9.40811 7.55789C9.48411 7.51689 9.57111 7.49489 9.65811 7.49789C9.74711 7.49989 10.1091 7.62689 10.2331 7.67589C11.2111 8.05589 13.2801 9.43389 14.0401 10.2439C14.1081 10.3169 14.2951 10.5129 14.3261 10.5529C14.3971 10.6429 14.4321 10.7519 14.4321 10.8619C14.4321 10.9639 14.4011 11.0679 14.3371 11.1549C14.3041 11.1999 14.1131 11.3999 14.0501 11.4669Z" stroke-linecap="round" stroke-linejoin="round"/></svg>
								</a>
								<button class="card__add" type="button"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M16,2H8A3,3,0,0,0,5,5V21a1,1,0,0,0,.5.87,1,1,0,0,0,1,0L12,18.69l5.5,3.18A1,1,0,0,0,18,22a1,1,0,0,0,.5-.13A1,1,0,0,0,19,21V5A3,3,0,0,0,16,2Zm1,17.27-4.5-2.6a1,1,0,0,0-1,0L7,19.27V5A1,1,0,0,1,8,4h8a1,1,0,0,1,1,1Z"/></svg></button>
								<span class="card__rating"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M22,9.67A1,1,0,0,0,21.14,9l-5.69-.83L12.9,3a1,1,0,0,0-1.8,0L8.55,8.16,2.86,9a1,1,0,0,0-.81.68,1,1,0,0,0,.25,1l4.13,4-1,5.68A1,1,0,0,0,6.9,21.44L12,18.77l5.1,2.67a.93.93,0,0,0,.46.12,1,1,0,0,0,.59-.19,1,1,0,0,0,.4-1l-1-5.68,4.13-4A1,1,0,0,0,22,9.67Zm-6.15,4a1,1,0,0,0-.29.88l.72,4.2-3.76-2a1.06,1.06,0,0,0-.94,0l-3.76,2,.72-4.2a1,1,0,0,0-.29-.88l-3-3,4.21-.61a1,1,0,0,0,.76-.55L12,5.7l1.88,3.82a1,1,0,0,0,.76.55l4.21.61Z"/></svg>{{mov.imdb}}</span>
								<h3 class="card__title"><a href="details.html">{{mov.title}}</a></h3>
								<ul class="card__list">
									<li>{{mov.genre|truncatewords:1}}</li>
									<li>{{mov.publish}}</li>
								</ul>
							</div>
						</div>
						{% endfor %}
					</div>
				</div>
			</div>		

			<div class="row">
				<div class="col-12">
					<a href="{% url 'movie:series-list' page=1 %}" ><button class="catalog__more" type="button">Load more</button></a>
				</div>
			</div>
		</div>
	</div>
	<!-- end catalog -->



{% endblock content %}

Movie/templates/shared/Header.html
{% load static %}
<header class="header header--static">
		<div class="container">
			<div class="row">
				<div class="col-12">
					<div class="header__content">
						<button class="header__menu" type="button">
							<span></span>
							<span></span>
							<span></span>
						</button>

						<a href="{% url 'movie:home' %}" class="header__logo">
							<img src="{% static 'img/logo.svg' %}" alt="Movies & TV Shows, Online cinema HTML Template">
						</a>

						<ul class="header__nav">
							<li class="header__nav-item">
								<a class="header__nav-link" href="{% url 'movie:home' %}">Home <svg width="4" height="4" viewBox="0 0 4 4" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M1.93893 3.30334C1.08141 3.30334 0.384766 2.60669 0.384766 1.75047C0.384766 0.894254 1.08141 0.196308 1.93893 0.196308C2.79644 0.196308 3.49309 0.894254 3.49309 1.75047C3.49309 2.60669 2.79644 3.30334 1.93893 3.30334Z"/></svg></a>
							</li>
							<li class="header__nav-item">
								<a class="header__nav-link" href="{% url 'movie:movie-list' page=1 %}">Movies<svg width="4" height="4" viewBox="0 0 4 4" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M1.93893 3.30334C1.08141 3.30334 0.384766 2.60669 0.384766 1.75047C0.384766 0.894254 1.08141 0.196308 1.93893 0.196308C2.79644 0.196308 3.49309 0.894254 3.49309 1.75047C3.49309 2.60669 2.79644 3.30334 1.93893 3.30334Z"/></svg></a>
							</li>
							<li class="header__nav-item">
								<a class="header__nav-link" href="{% url 'movie:series-list' page=1 %}">Series<svg width="4" height="4" viewBox="0 0 4 4" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M1.93893 3.30334C1.08141 3.30334 0.384766 2.60669 0.384766 1.75047C0.384766 0.894254 1.08141 0.196308 1.93893 0.196308C2.79644 0.196308 3.49309 0.894254 3.49309 1.75047C3.49309 2.60669 2.79644 3.30334 1.93893 3.30334Z"/></svg></a>
							</li>
						</ul>

						<div class="header__actions">
							<form action="/search/" class="header__form">
								<input class="header__form-input" type="text" placeholder="I'm looking for..." name="q">
								<button class="header__form-btn" type="button"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M21.71,20.29,18,16.61A9,9,0,1,0,16.61,18l3.68,3.68a1,1,0,0,0,1.42,0A1,1,0,0,0,21.71,20.29ZM11,18a7,7,0,1,1,7-7A7,7,0,0,1,11,18Z"/></svg></button>
								<button type="button" class="header__form-close"><svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" clip-rule="evenodd" d="M14.3345 0.000183105H5.66549C2.26791 0.000183105 0.000488281 2.43278 0.000488281 5.91618V14.0842C0.000488281 17.5709 2.26186 20.0002 5.66549 20.0002H14.3335C17.7381 20.0002 20.0005 17.5709 20.0005 14.0842V5.91618C20.0005 2.42969 17.7383 0.000183105 14.3345 0.000183105ZM5.66549 1.50018H14.3345C16.885 1.50018 18.5005 3.23515 18.5005 5.91618V14.0842C18.5005 16.7653 16.8849 18.5002 14.3335 18.5002H5.66549C3.11525 18.5002 1.50049 16.7655 1.50049 14.0842V5.91618C1.50049 3.23856 3.12083 1.50018 5.66549 1.50018ZM7.07071 7.0624C7.33701 6.79616 7.75367 6.772 8.04726 6.98988L8.13137 7.06251L9.99909 8.93062L11.8652 7.06455C12.1581 6.77166 12.6329 6.77166 12.9258 7.06455C13.1921 7.33082 13.2163 7.74748 12.9984 8.04109L12.9258 8.12521L11.0596 9.99139L12.9274 11.8595C13.2202 12.1524 13.2202 12.6273 12.9273 12.9202C12.661 13.1864 12.2443 13.2106 11.9507 12.9927L11.8666 12.9201L9.99898 11.052L8.13382 12.9172C7.84093 13.2101 7.36605 13.2101 7.07316 12.9172C6.80689 12.6509 6.78269 12.2343 7.00054 11.9407L7.07316 11.8566L8.93843 9.99128L7.0706 8.12306C6.77774 7.83013 6.77779 7.35526 7.07071 7.0624Z"/></svg></button>
							</form>

							<button class="header__search" type="button">
								<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M21.71,20.29,18,16.61A9,9,0,1,0,16.61,18l3.68,3.68a1,1,0,0,0,1.42,0A1,1,0,0,0,21.71,20.29ZM11,18a7,7,0,1,1,7-7A7,7,0,0,1,11,18Z"/></svg>
							</button>

							<a href="" class="header__user">
								<span>Sign in</span>
								<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M20,12a1,1,0,0,0-1-1H11.41l2.3-2.29a1,1,0,1,0-1.42-1.42l-4,4a1,1,0,0,0-.21.33,1,1,0,0,0,0,.76,1,1,0,0,0,.21.33l4,4a1,1,0,0,0,1.42,0,1,1,0,0,0,0-1.42L11.41,13H19A1,1,0,0,0,20,12ZM17,2H7A3,3,0,0,0,4,5V19a3,3,0,0,0,3,3H17a3,3,0,0,0,3-3V16a1,1,0,0,0-2,0v3a1,1,0,0,1-1,1H7a1,1,0,0,1-1-1V5A1,1,0,0,1,7,4H17a1,1,0,0,1,1,1V8a1,1,0,0,0,2,0V5A3,3,0,0,0,17,2Z"/></svg>
							</a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</header>

Movie/templates/shared/_Footer_Refrences.html
{% load static %}
    <!-- JS -->
	<script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
	<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
	<script src="{% static 'js/owl.carousel.min.js' %}"></script>
	<script src="{% static 'js/slider-radio.js' %}"></script>
	<script src="{% static 'js/select2.min.js' %}"></script>
	<script src="{% static 'js/smooth-scrollbar.js' %}"></script>
	<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
	<script src="{% static 'js/plyr.min.js' %}"></script>
	<script src="{% static 'js/main.js' %}"></script>